# Generated by Django 2.2.2 on 2021-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=32)),
                ('gender', models.TextField(blank=True, verbose_name='过后感想')),
                ('mobile', models.TextField(blank=True, verbose_name='过后感想')),
            ],
        ),
    ]
