# Generated by Django 2.2.2 on 2021-09-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
